### ISSUE TITLE
Dingo Api

### ISSUE THREAD

**Issue by ethersport-io** [fntneves/laravel-transactional-events#16]
Hello.
After installing the package, I get a conflict:
Argument 1 passed to Dingo\Api\Http\Response::setEventDispatcher() must be an instance of Illuminate\Events\Dispatcher, instance of Neves\Events\TransactionalDispatcher given, called in ../vendor/dingo/api/src/Provider/DingoServiceProvider.php on line 37

**Comment by fntneves** [comment]
Hello,

The problem is that Dingo is expecting the original Event Dispatcher class, not the Event Dispatcher interface.

`TransactionalDispatcher` implements that interface, rather than extending the Event Dispatcher class. Therefore, it is not compatible with Dingo.

We can solve this by opening an issue in Dingo's repository and see if they can change it. (Sentry also changed it in their driver's code).
