### ISSUE TITLE
Conflict with Clockwork

### ISSUE THREAD

**Issue by terranc** [fntneves/laravel-transactional-events#17]
![image](https://user-images.githubusercontent.com/224353/45852711-c04d9a00-bd73-11e8-8607-18474ff51316.png)

**Comment by fntneves** [comment]
Hello @terranc,

Thank you for opening this issue.

This is a common issue that also happens in other repositories:
- https://github.com/fntneves/laravel-transactional-events/issues/16
- https://github.com/fntneves/laravel-transactional-events/pull/15

It is happening due to the type hinting they are using. They are expecting an instance of concrete classe Event Dispatcher and `TransactionalDispatcher` implements the contract.

However, 10 months ago there is a commit that fixes it: https://github.com/itsgoingd/clockwork/commit/d1ccbf150c6117fb8cd463e8365aef6db6a20ce7

Can you update your clockwork package and see if this is still happening?

**Comment by terranc** [comment]
the same is error

**Comment by fntneves** [comment]
Ok, no problem. I will release a new version with TransactionalDispatcher extending the original Event Dispatcher.

**Comment by terranc** [comment]
v2.2

**Comment by fntneves** [comment]
The version of Clockwork that includes this change is v3.0+.

**Comment by terranc** [comment]
fixed, thank you
