### ISSUE TITLE
Issue when transaction done on non-default connection

### ISSUE THREAD

**Issue by jitendra-1217** [fntneves/laravel-transactional-events#19]
__Brief__

When inside a transaction on non-default database connection, events dispatched are not actually dispatched after transaction commit.

---

__Debug__

Reproducible with following sample snippet.

```php
DB::connection('zone-b')->transaction(function() { event(new \App\Events\SampleEvent); });
```

In below line we use `->connection()` method of resolver class which returns default connection i.e. connection against default connection name (say `zone-a`, refer config/database.php). And hence from the implementation it never is pushed in `$pendingEvents`.

https://github.com/fntneves/laravel-transactional-events/blob/21e69c2a6a6de692bcacfcda25c7521fa5d8601d/src/Neves/Events/TransactionalDispatcher.php#L84-L86

---

__Proposed Fix__

Update:

1. Using a stack of connection names/ids. Every transaction start, push it over, every commit/rollback dispatch/discard pending events of popped txn. How is it?

**Comment by jitendra-1217** [comment]
Also what is your thought on [this implementation](https://github.com/therezor/laravel-transactional-jobs/blob/master/src/TransactionalDispatcher.php)? It is not mine.

1. It seems to plug at a layer where event() and Jobs::dispatch() both work.
2. It seems like handling nested transaction etc and doesn't have those maps per connection name.

**Comment by fntneves** [comment]
Hi @jitendra-1217,

First of all, let me thank you for opening this issue. I always see it as a chance to improve the package.

I see this issue as a limitation of this package. Thus, I believe it could be a great improvement.

I will build up a regression test in order to reproduce this issue and then try to figure out what could be done to fix it.

Regarding your proposed fix, it seems an effective approach. However, I am afraid that transaction levels on the same connection, i.e. nested transactions, may get it a bit more complicated.

The implementation of the package you've mentioned seems incomplete to me. It does not handle different connections also and is related to jobs themselves, not events that triggers jobs.

Are you interested to open a PR?

**Comment by jitendra-1217** [comment]
> Are you interested in opening a PR?

Yes.
Unfortunately, will be able to get back to this in 3 weeks time. Have some other priorities now till then.

**Comment by jitendra-1217** [comment]
I ended up writing https://github.com/jitendra-1217/lqext instead.

For my use cases had to add few other supports as well e.g. handling all kind of dispatches besides Event dispatcher which this repo handles. All kinds includes - Bus, queued job dispatching, mailables etc. Also had to support queue failures etc. And for these reasons ended up writing a new lib.

Your repository has been a great help.
