### ISSUE TITLE
Question: seeking clarification regarding Laravels native events

### ISSUE THREAD

**Issue by mfn** [fntneves/laravel-transactional-events#29]
Upfront, thanks for the package!

Re-reading the README and looking at `config/transactional-events.php` I'm not _entirely_ in the clear what events by default would be handled transactional.

I've also looked at `\Neves\Events\TransactionalDispatcher::shouldHandle` to get a better picture.

> What I want to achieve is a total "opt-in" for transactional events
>- No event without explicit consent should be handled transactionally.
>- Only application specific events should be handled transactionally

My understand is, to achieve that, the following approach would be correct
- enable in config (doh!)
- do _not_ listen any events in `'transactional'`
- the value of `'excluded'` actual does not matter

Config (condensed a bit):
```php
<?php declare(strict_types = 1);

return [

    'enable' => true,

    'transactional' => [
        // 'App\Events',
    ],

    'excluded' => [
        // 'eloquent.*',
        'eloquent.booted',
        'eloquent.retrieved',
        'eloquent.saved',
        'eloquent.updated',
        'eloquent.created',
        'eloquent.deleted',
        'eloquent.restored',
    ],
];
```

I _think_ my assumptions are right, however I'm not sure why the excluded lists the eloquent event. Based on the code in the dispatcher, I would not understand why Eloquent events would be considered for transaction in the first place anyway. That would require them to listed in `'transactional'`, e.g. like `eloquent.*`, no?

Thanks for clarification!

**Comment by fntneves** [comment]
Hello @mfn,

The opt-in you want is in runtime, or without changing the configuration everytime you want to mark event as transactional?

The former case is not achievable with this package.

In the latter case, you should leverage the `TransactionalEvent` contract, which works as a tag for each event and has the highest priority over the configuration file. That is, every single event that implements the `TransactionalEvent` contract is handled as transactional, even if it is specified in the `excluded` configuration property.

>I'm not sure why the excluded lists the eloquent event. Based on the code in the dispatcher, I would not understand why Eloquent events would be considered for transaction in the first place anyway. That would require them to listed in 'transactional', e.g. like eloquent.*, no?

This package, out of the box, hints that excluding Eloquent native `*ed` events is a right choice because making them transactional could interfere with already implemented application's logic for new installations.  For enabling such Eloquent events, yes, the only way is to add them to `transactional`. However, you still can exclude some of them by adding them to the `excluded` configuration property.

**Comment by mfn** [comment]
Sorry my confusing question, it was only targeting this part:
>  or without changing the configuration everytime you want to mark event as transactional?

Your answer is exactly as I'd hoped / understand, just wanted to ensure I understand it.

Thank you!
