### ISSUE TITLE
Errror In TransactionalDispatcher on line 72

### ISSUE THREAD

**Issue by ossycodes** [fntneves/laravel-transactional-events#45]
![1](https://user-images.githubusercontent.com/55060799/95852793-4585bc00-0d4c-11eb-82e2-fc4f67443f2f.PNG)

Using version Laravel 5.8 and 1.8.x of your package

**Comment by mfn** [comment]
Thanks for the report!

In general, pleaste paste the actual text of the terminal output instead of screenshots.

That said…
---
This "seems" like a bug in this package, from just reading the code in https://github.com/fntneves/laravel-transactional-events/blob/571c965b47deb43492d25fe9024bfa1f820abf48/src/Neves/Events/TransactionalDispatcher.php#L67-L76

`$eventDispatcher` is expected to be of the concrete type `Illuminate\Events\Dispatcher` but the phpdoc actually says it should be the contract `Illuminate\Contracts\Events\Dispatcher`, as does the property itself https://github.com/fntneves/laravel-transactional-events/blob/571c965b47deb43492d25fe9024bfa1f820abf48/src/Neves/Events/TransactionalDispatcher.php#L24

Maybe just an oversight? 🤔

Can you locally apply the changes from https://github.com/fntneves/laravel-transactional-events/pull/46 and see if it works for you?

**Comment by fntneves** [comment]
It is a bug, actually. The docblock is the expected behavior. Thank you for opening this issue!

**Comment by ossycodes** [comment]
Thanks ! that works!

**Comment by fntneves** [comment]
I'm preparing a new patch release. 👍

**Comment by ossycodes** [comment]
please do, currently using this in prod
