### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by Szasza** [fntneves/laravel-transactional-events#7]
Hi @fntneves ,

First of all, thank you for providing the package.

I would like to ask if you'd accept a PR which requires individual Illuminate packages instead of the Laravel framework, therefore it would be compatible with Lumen as well.

If so, I am happy to make the changes.

Cheers,
Szasza

**Comment by fntneves** [comment]
Hello @Szasza,

Thank you in advance for opening this issue and for your intention to contribute.

In fact, I am able to accept PRs for this purpose. Since I never used Lumen for my projects, I limited it to Laravel. However, I agree that it should support Lumen, since it belongs to the Laravel community.

Therefore, I would be glad to have and review your PR, for sure!

Best,
Francisco Neves

**Comment by Szasza** [comment]
Hi @fntneves,

Great, thank you, will get it sorted over the weekend.

Cheers,
Szasza
